version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "-O", "main.py"]
