version: '3.8'

services:
  mongodb:
    image: mongo:4.4.11-rc0-focal
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - vinted-network

  bot:
    depends_on:
      - mongodb
    build: .
    volumes:
      - ./data:/app/data
      - ./config.json:/app/config.json
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_URI=mongodb://mongodb:27017
    command: ["python", "-O", "main.py"]
    networks:
      - vinted-network

volumes:
  mongodb_data:
  
networks:
      - vinted-network
